
package org.pathvisio;

// Do not modify, this file is automatically generated
public class Revision
{
	public static final String REVISION = "${subversion_revision}";
	public static final String VERSION = "2.0.5";
}
	  